/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/*JFileChooser chooser = new JFileChooser("C:/Users/paras/Desktop/projectImage/back white");
        // chooser.showOpenDialog(null);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
         filePath = f.getAbsolutePath();
            // txt_path.setText(filename)
            FilePath file_path = new FilePath();//creat new class to store the directory path
            file_path.setFilePath(filePath);//setinh path
            System.out.println("name==" + filePath);
            ImageIcon imgThisImg = new ImageIcon(filePath);
            img_lbl.setIcon(imgThisImg);*/



package com.nce.project;

import com.paddy.kmeans.KMeansSegmentation;
import com.paddy.project.daoimp.GetWeightDaoImp;
import com.paddy.project.daoimp.GetingOutputDaoImp;
import com.paddy.project.model.MatchingPercent;
import com.paddy.project.neuralnetwork.FeedForwardNeuralNetwork;
import com.paddy.project.operation.OperationUtility;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author paras
 */
public class TestWindow extends javax.swing.JFrame {
    
    static String filePath=null;
    BufferedImage image;
    BufferedImage image1;
    BufferedImage image2;
    BufferedImage image3;
    BufferedImage image4;
    

    /**
     * Creates new form TestWindow
     */
    public TestWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoadImage_Btn = new javax.swing.JButton();
        Test_ExtractFeature_Btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        lbloriginalimg = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        lblclusteroneimg = new javax.swing.JLabel();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        lblclustertwoimg = new javax.swing.JLabel();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        lblclusterthreeimg = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cluster_btn = new javax.swing.JButton();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        lblclusterfourimg = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoadImage_Btn.setBackground(new java.awt.Color(255, 255, 255));
        LoadImage_Btn.setText("Load Image");
        LoadImage_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadImage_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(LoadImage_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 170, 60));

        Test_ExtractFeature_Btn.setBackground(new java.awt.Color(255, 255, 255));
        Test_ExtractFeature_Btn.setText("Test Here");
        Test_ExtractFeature_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Test_ExtractFeature_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(Test_ExtractFeature_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 170, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Test Session");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 840, 20));

        jDesktopPane1.add(lbloriginalimg);
        lbloriginalimg.setBounds(0, 0, 260, 220);

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 260, 220));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 255));
        jLabel3.setText("               Cluster Fourth");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 210, 20));

        jDesktopPane3.add(lblclusteroneimg);
        lblclusteroneimg.setBounds(0, 0, 260, 220);

        getContentPane().add(jDesktopPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 260, 220));

        jDesktopPane4.add(lblclustertwoimg);
        lblclustertwoimg.setBounds(0, 0, 260, 220);

        getContentPane().add(jDesktopPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 260, 220));

        lblclusterthreeimg.setText("jLabel2");
        jDesktopPane2.add(lblclusterthreeimg);
        lblclusterthreeimg.setBounds(0, 0, 260, 220);

        getContentPane().add(jDesktopPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 260, 220));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("               Selected Image ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 210, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 102, 255));
        jLabel5.setText("                Cluster First");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 210, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("               Cluster Second");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 240, 210, 20));

        cluster_btn.setBackground(new java.awt.Color(255, 255, 255));
        cluster_btn.setText("K-Means Cluster");
        cluster_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cluster_btnActionPerformed(evt);
            }
        });
        getContentPane().add(cluster_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 170, 60));

        lblclusterfourimg.setText("jLabel2");
        jDesktopPane5.add(lblclusterfourimg);
        lblclusterfourimg.setBounds(0, 0, 260, 220);

        getContentPane().add(jDesktopPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 260, 220));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 255));
        jLabel7.setText("              Cluster Third");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 210, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Test_ExtractFeature_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Test_ExtractFeature_BtnActionPerformed
        FilePath fPath=new FilePath();
        double[] inputFeature;

        try {
            BufferedImage image = ImageIO.read(new File(fPath.getFilePath()));
            FeatureExtractionForTest fTest=new FeatureExtractionForTest();
            ArrayList<String> bin_feature =fTest.getBinFeatures(image);
            inputFeature=new double[bin_feature.size()];
            for(int i=0;i<inputFeature.length;i++){
                inputFeature[i]=Double.valueOf(bin_feature.get(i));
            }

            GetWeightDaoImp getWT=new GetWeightDaoImp();
            double[][] weight_at_hidden_layer=getWT.getAdjustedWeightAtHiddenLayer();
            double[] weight_at_output_layer=getWT.getAdjustedWeightAtOutputLayer();

            FeedForwardNeuralNetwork FFNetwork=new FeedForwardNeuralNetwork();
            double output=FFNetwork.testNeralNetwork(inputFeature,weight_at_hidden_layer,weight_at_output_layer);
            System.out.println(output);
            GetingOutputDaoImp G=new GetingOutputDaoImp();
            String disease_name=G.getDetectedDiseaseName(output);
            MatchingPercent m=new MatchingPercent();//get percetage matching
            if(m.getMatchedPercentage()>=99){

                JOptionPane.showMessageDialog(null,"Detected Disease is  = "+disease_name+"    Matching=="+m.getMatchedPercentage()+"%");
            }

            else{
                JOptionPane.showMessageDialog(null,"Sorry System Has Not Got Any Matched with System's Database");

            }

        } catch (IOException ex) {
            Logger.getLogger(TestWindow.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_Test_ExtractFeature_BtnActionPerformed

    private void LoadImage_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadImage_BtnActionPerformed

        JFileChooser chooser = new JFileChooser("C:/Users/985570/Desktop/Raju_Machine_Learning/Project");
        // chooser.showOpenDialog(null);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            filePath = f.getAbsolutePath();
            // txt_path.setText(filename)
            FilePath file_path = new FilePath();//creat new class to store the directory path
            file_path.setFilePath(filePath);//setinh path
            System.out.println("name==" + filePath);
            ImageIcon imgThisImg = new ImageIcon(filePath);
            lbloriginalimg.setIcon(imgThisImg);

        }

    }//GEN-LAST:event_LoadImage_BtnActionPerformed

    private void cluster_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cluster_btnActionPerformed
        
        try {
            image = ImageIO.read(new File(filePath));
            image1 = ImageIO.read(new File(filePath));
            image2 = ImageIO.read(new File(filePath));
            image3 = ImageIO.read(new File(filePath));
            image4 = ImageIO.read(new File(filePath));
            
        } catch (IOException ex) {
            Logger.getLogger(TestWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
       KMeansSegmentation kMeansSegmentation = new KMeansSegmentation();
        ArrayList<BufferedImage> list=kMeansSegmentation.clustering(image,image1,image2,image3,image4);
        lblclusteroneimg.setIcon(new ImageIcon(list.get(0)));
        lblclustertwoimg.setIcon(new ImageIcon(list.get(1)));
        lblclusterthreeimg.setIcon(new ImageIcon(list.get(2)));
        lblclusterfourimg.setIcon(new ImageIcon(list.get(3)));
        OperationUtility operationUtility=new OperationUtility();
        List<Integer> clusterDescription= operationUtility.getDescriptionOfClusteredImages(list);
        JOptionPane.showMessageDialog(null,"Cluster 1 and 4 gives Most damaged part of leaf and is = "+(clusterDescription.get(0)+clusterDescription.get(3))+"% ,"
                + "\n\nCluster Third gives Less damaged part of leaf and is = "+clusterDescription.get(2)+"%"
                + "\n\nCluster second gives Non-damaged OR very Less damaged part of leaf and is = "+clusterDescription.get(1)+"% ");
        
        
    }//GEN-LAST:event_cluster_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoadImage_Btn;
    private javax.swing.JButton Test_ExtractFeature_Btn;
    private javax.swing.JButton cluster_btn;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblclusterfourimg;
    private javax.swing.JLabel lblclusteroneimg;
    private javax.swing.JLabel lblclusterthreeimg;
    private javax.swing.JLabel lblclustertwoimg;
    private javax.swing.JLabel lbloriginalimg;
    // End of variables declaration//GEN-END:variables

}
