/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nce.project;

import com.paddy.project.daoimp.GetInputFeatureDaoImp;
import com.paddy.project.daoimp.GetTargetOutputDaoImp;
import com.paddy.project.daoimp.GetWeightDaoImp;
import com.paddy.project.model.InputPattern;
import com.paddy.project.neuralnetwork.BackPropagationNeuralNetwork;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author paras
 */
public class TrainingWindow extends javax.swing.JFrame {

    /**
     * Creates new form TrainingWindow
     */
    public TrainingWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoadImageFolder_Btn = new javax.swing.JButton();
        Disease_ComboBox = new javax.swing.JComboBox();
        TrainingFeature_Btn = new javax.swing.JButton();
        StartTraining_Btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoadImageFolder_Btn.setBackground(new java.awt.Color(255, 255, 255));
        LoadImageFolder_Btn.setText("Load Image Folder");
        LoadImageFolder_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadImageFolder_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(LoadImageFolder_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 43, 160, 50));

        Disease_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blast", "BrownSpot" }));
        getContentPane().add(Disease_ComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 160, 50));

        TrainingFeature_Btn.setBackground(new java.awt.Color(255, 255, 255));
        TrainingFeature_Btn.setText("Feature Extract");
        TrainingFeature_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrainingFeature_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(TrainingFeature_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 160, 50));

        StartTraining_Btn.setBackground(new java.awt.Color(255, 255, 255));
        StartTraining_Btn.setText("Start Training");
        StartTraining_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartTraining_BtnActionPerformed(evt);
            }
        });
        getContentPane().add(StartTraining_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 160, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Training Session");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 620, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nce/project/training_testing.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 470, 410));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoadImageFolder_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadImageFolder_BtnActionPerformed
        JFileChooser chooser = new JFileChooser("C:/Users/985570/Desktop/Raju_Machine_Learning/Project");
        // chooser.showOpenDialog(null);
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File f = chooser.getSelectedFile();
            folderName = f.getAbsolutePath();
            // txt_path.setText(filename)
            FilePath file_path = new FilePath();//creat new class to store the directory path
            file_path.setFilePath(folderName);//setinh path
            System.out.println("name==" + folderName);

    }//GEN-LAST:event_LoadImageFolder_BtnActionPerformed
    }
    private void TrainingFeature_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrainingFeature_BtnActionPerformed
       
        if(folderName==null){
         JOptionPane.showMessageDialog(null, "Choose Atleast One Image Containing Folder First !!");
        }else{
        String disease_name = Disease_ComboBox.getSelectedItem().toString();
        disease_countt++;
       
        
        ReadMultipleImage rd = new ReadMultipleImage(folderName);
        
        boolean ftest = rd.extractAndSaveFeaures(disease_countt, disease_name);
        if (ftest) {
            JOptionPane.showMessageDialog(null, "Feature Extraction Completed");
        } else {
            JOptionPane.showMessageDialog(null, "Error In Feature Extraction");
        }
        }
        folderName=null;
    }//GEN-LAST:event_TrainingFeature_BtnActionPerformed

    private void StartTraining_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartTraining_BtnActionPerformed

        GetInputFeatureDaoImp feature = new GetInputFeatureDaoImp();
        double[][] inputFeature = feature.getInputFeature();
        GetWeightDaoImp weight = new GetWeightDaoImp();
        double[][] weight_at_hidden_layer = weight.getWeightAtHiddenLayer();
        double[] weight_at_output_layer = weight.getWeightAtOutputLayer();
        GetTargetOutputDaoImp getTO = new GetTargetOutputDaoImp();
        double[] target_output = getTO.getTargetOutput();
        for(double to:target_output){
        System.out.println("target output=="+to);
        }
        InputPattern iP = new InputPattern();
        int no_of_pattern = iP.getTotal_input_pattern();
        System.out.println(no_of_pattern);
        BackPropagationNeuralNetwork NN = new BackPropagationNeuralNetwork(no_of_pattern);
        boolean status=NN.trainNeuralNetwork(inputFeature, weight_at_hidden_layer, weight_at_output_layer, target_output);
       if(status){
           JOptionPane.showMessageDialog(null,"Congratulation Training completed");
       }
        


    }//GEN-LAST:event_StartTraining_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainingWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainingWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Disease_ComboBox;
    private javax.swing.JButton LoadImageFolder_Btn;
    private javax.swing.JButton StartTraining_Btn;
    private javax.swing.JButton TrainingFeature_Btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
   String folderName = null;
    int disease_countt = 0;
}
